// signin
export const AUTH = "AUTH";
export const FETCH_SINGLEUSER = "FETCH_SINGLEUSER";
export const LOGOUT = "LOGOUT";
export const UPDATE_SINGLE_USER = "UPDATE_SINGLE_USER";
export const IS_LOADING = "IS_LOADING";
export const IS_NOT_LOADING = "IS_NOT_LOADING";
export const FETCH_USERS = "FETCH_USERS";

// homePage
export const FETCH_HOMEPAGE = "FETCH_HOMEPAGE";
export const CREATE_HOMEPAGE = "CREATE_HOMEPAGE";
export const START_HOMEPAGE = "START_HOMEPAGE";
export const END_HOMEPAGE = "END_HOMEPAGE";
export const DELETE_HOMEPAGE = "DELETE_HOMEPAGE";
export const UPDATE_HOMEPAGE = "UPDATE_HOMEPAGE";

// foodPage
export const FETCH_FOODPAGE = "FETCH_FOODPAGE";
export const FETCH_FOOD_BY_SEARCH = "FETCH_FOOD_BY_SEARCH";
export const CREATE_FOODPAGE = "CREATE_FOODPAGE";
export const START_FOODPAGE = "START_FOODPAGE";
export const END_FOODPAGE = "END_FOODPAGE";
export const DELETE_FOODPAGE = "DELETE_FOODPAGE";
export const UPDATE_FOODPAGE = "UPDATE_FOODPAGE";
export const FETCH_FOODPAGE_BY_ID = "FETCH_FOODPAGE_BY_ID";
export const UPDATE_COMMENT_FOOD = "UPDATE_COMMENT_FOOD";
export const DELETE_COMMENT_FOOD = "DELETE_COMMENT_FOOD";

// payment
export const FETCH_PAYMENT_FOOD = "FETCH_PAYMENT_FOOD";
export const FETCH_PAYMENT_CLIENT_FOOD = "FETCH_PAYMENT_CLIENT_FOOD";
export const FETCH_PAYMENT_DELETE = "FETCH_PAYMENT_DELETE";
export const START_PAYMENT = "START_PAYMENT";
export const END_PAYMENT = "END_PAYMENT";

// Add room by Admin
export const ROOM_CREATE_REQUEST = "ROOM_CREATE_REQUEST";
export const ROOM_CREATE_SUCCESS = "ROOM_CREATE_SUCCESS";
export const ROOM_CREATE_FAIL = "ROOM_CREATE_FAIL";
export const ROOM_CREATE_RESET = "ROOM_CREATE_RESET";

// List of rooms
export const ROOM_LIST_REQUEST = "ROOM_LIST_REQUEST";
export const ROOM_LIST_SUCCESS = "ROOM_LIST_SUCCESS";
export const ROOM_LIST_FAIL = "ROOM_LIST_FAIL";

// Contact Us
export const CONTACT_US_REQUEST = "CONTACT_US_REQUEST";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAIL = "CONTACT_US_FAIL";
export const CONTACT_US_RESET = "CONTACT_US_RESET";

// Contact Us Resolved
export const CONTACT_US_RESOLVE_REQUEST = "CONTACT_US_RESOLVE_REQUEST";
export const CONTACT_US_RESOLVE_SUCCESS = "CONTACT_US_RESOLVE_SUCCESS";
export const CONTACT_US_RESOLVE_FAIL = "CONTACT_US_RESOLVE_FAIL";

// Contact Us List
export const CONTACT_US_LIST_REQUEST = "CONTACT_US_LIST_REQUEST";
export const CONTACT_US_LIST_SUCCESS = "CONTACT_US_LIST_SUCCESS";
export const CONTACT_US_LIST_FAIL = "CONTACT_US_LIST_FAIL";

// Delete Contact Us
export const CONTACT_US_DELETE_REQUEST = "CONTACT_US_DELETE_REQUEST";
export const CONTACT_US_DELETE_SUCCESS = "CONTACT_US_DELETE_SUCCESS";
export const CONTACT_US_DELETE_FAIL = "CONTACT_US_DELETE_FAIL";

// List of Booked rooms
export const ROOM_BOOKED_LIST_REQUEST = "ROOM_BOOKED_LIST_REQUEST";
export const ROOM_BOOKED_LIST_SUCCESS = "ROOM_BOOKED_LIST_SUCCESS";
export const ROOM_BOOKED_LIST_FAIL = "ROOM_BOOKED_LIST_FAIL";

// Booked Room Detail
export const ROOM_BOOKED_DETAILS_REQUEST = "ROOM_BOOKED_DETAILS_REQUEST";
export const ROOM_BOOKED_DETAILS_SUCCESS = "ROOM_BOOKED_DETAILS_SUCCESS";
export const ROOM_BOOKED_DETAILS_FAIL = "ROOM_BOOKED_DETAILS_FAIL";

// Delete Booked Rooms
export const ROOM_BOOKED_DELETE_REQUEST = "ROOM_BOOKED_DELETE_REQUEST";
export const ROOM_BOOKED_DELETE_SUCCESS = "ROOM_BOOKED_DELETE_SUCCESS";
export const ROOM_BOOKED_DELETE_FAIL = "ROOM_BOOKED_DELETE_FAIL";

// List of My Booked rooms
export const ROOM_BOOKED_APPROVE_REQUEST = "ROOM_BOOKED_APPROVE_REQUEST";
export const ROOM_BOOKED_APPROVE_SUCCESS = "ROOM_BOOKED_APPROVE_SUCCESS";
export const ROOM_BOOKED_APPROVE_FAIL = "ROOM_BOOKED_APPROVE_FAIL";

// Pay Booked rooms
export const ROOM_BOOKED_PAYMENT_REQUEST = "ROOM_BOOKED_PAYMENT_REQUEST";
export const ROOM_BOOKED_PAYMENT_SUCCESS = "ROOM_BOOKED_PAYMENT_SUCCESS";
export const ROOM_BOOKED_PAYMENT_FAIL = "ROOM_BOOKED_PAYMENT_FAIL";

// Update room by Admin
export const ROOM_UPDATE_REQUEST = "ROOM_UPDATE_REQUEST";
export const ROOM_UPDATE_SUCCESS = "ROOM_UPDATE_SUCCESS";
export const ROOM_UPDATE_FAIL = "ROOM_UPDATE_FAIL";
export const ROOM_UPDATE_RESET = "ROOM_UPDATE_RESET";

// Approve booked rooms
export const ROOM_MY_BOOKED_LIST_REQUEST = "ROOM_MY_BOOKED_LIST_REQUEST";
export const ROOM_MY_BOOKED_LIST_SUCCESS = "ROOM_MY_BOOKED_LIST_SUCCESS";
export const ROOM_MY_BOOKED_LIST_FAIL = "ROOM_MY_BOOKED_LIST_FAIL";

// Delete room by Admin
export const ROOM_DELETE_REQUEST = "ROOM_DELETE_REQUEST";
export const ROOM_DELETE_SUCCESS = "ROOM_DELETE_SUCCESS";
export const ROOM_DELETE_FAIL = "ROOM_DELETE_FAIL";

// Room Booking By Client
export const ROOM_BOOK_REQUEST = "ROOM_BOOK_REQUEST";
export const ROOM_BOOK_SUCCESS = "ROOM_BOOK_SUCCESS";
export const ROOM_BOOK_FAIL = "ROOM_BOOK_FAIL";
export const ROOM_BOOK_RESET = "ROOM_BOOK_RESET";

// Review Room By Client
export const ROOM_CREATE_REVIEW_REQUEST = "ROOM_CREATE_REVIEW_REQUEST";
export const ROOM_CREATE_REVIEW_SUCCESS = "ROOM_CREATE_REVIEW_SUCCESS";
export const ROOM_CREATE_REVIEW_FAIL = "ROOM_CREATE_REVIEW_FAIL";
export const ROOM_CREATE_REVIEW_RESET = "ROOM_CREATE_REVIEW_RESET";

// Reply Room Review By Client
export const ROOM_REPLY_REVIEW_REQUEST = "ROOM_REPLY_REVIEW_REQUEST";
export const ROOM_REPLY_REVIEW_SUCCESS = "ROOM_REPLY_REVIEW_SUCCESS";
export const ROOM_REPLY_REVIEW_FAIL = "ROOM_REPLY_REVIEW_FAIL";
export const ROOM_REPLY_REVIEW_RESET = "ROOM_REPLY_REVIEW_RESET";

// Single Room Details
export const ROOM_DETAILS_REQUEST = "ROOM_DETAILS_REQUEST";
export const ROOM_DETAILS_SUCCESS = "ROOM_DETAILS_SUCCESS";
export const ROOM_DETAILS_FAIL = "ROOM_DETAILS_FAIL";
